name: Question
description: Ask a question about the project
title: "[Question]: "
labels: ["question"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Have a question? We're here to help! Please check the documentation first:
        - [README](../EMAIL_ASSISTANT_COMPLETE_README.md)
        - [Quick Start Guide](../QUICK_START.md)
        - [Contributing Guide](../CONTRIBUTING.md)

  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: What would you like to know?
      placeholder: Please be as specific as possible
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Question Category
      description: What is your question about?
      options:
        - Setup/Installation
        - Configuration
        - Usage/How-to
        - API/Development
        - Troubleshooting
        - Best Practices
        - Other
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Provide any relevant context
      placeholder: |
        - What have you tried so far?
        - What are you trying to accomplish?
        - Any relevant error messages?

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: If relevant, describe your environment
      placeholder: |
        - OS: [e.g. macOS, Windows, Linux]
        - Node version: [e.g. 18.0.0]
        - Browser: [e.g. Chrome 120]

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Before asking
      options:
        - label: I have read the documentation
          required: true
        - label: I have searched existing issues
          required: true
        - label: This is not a bug report or feature request
          required: true
